language: go
go:
  - 1.9.x
  - 1.10.x
  - tip
sudo: false
cache:
  directories:
    - vendor
    - _internal_bin/$(go version | awk '{ print $NF }')
install:
  - make installdeps
script:
  - make test
  - make all
